name: Codesing Automated Test Workflow.

on:
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  test:
    name: Codesign-Automated-Test
    runs-on: bluey-CMU
    steps:
      - name: Remove old workspace
        run: |
          rm -rf *
          rm -rf .[^.] .??*
          
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Debug-echo
        run: |
          echo ">>> CI is running inside Python Tests workflow on $(date)"
          echo "Current directory: $(pwd)"
          ls -la
        
      - name: Set up bash and run environment setup
        run: |
          chmod +x full_env_start.sh || true
          OPENROAD_PRE_INSTALLED=1 ./full_env_start.sh

      - name: Run Codesign Script
        run: |
          chmod +x test/automated_test_scripts/automated-scripts.sh || true
          ./test/automated_test_scripts/automated-scripts.sh

